<a href="https://colab.research.google.com/github/kulkarni-harsh/Plotix/blob/main/LinearRegressionModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import pandas as pd
import io
  
df = pd.read_csv(io.BytesIO(uploaded['student-mat.csv']),sep=';')
print(df)

    school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0       GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1       GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2       GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3       GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4       GP   F   16       U     GT3       T  ...     2       5        4   6  10  10
..     ...  ..  ...     ...     ...     ...  ...   ...     ...      ...  ..  ..  ..
390     MS   M   20       U     LE3       A  ...     5       4       11   9   9   9
391     MS   M   17       U     LE3       T  ...     4       2        3  14  16  16
392     MS   M   21       R     GT3       T  ...     3       3        3  10   8   7
393     MS   M   18       R     LE3       T  ...     4       5        0  11  12  10
394     MS   M   19       U     LE3       T  ...     3       5        5   8 

In [28]:
print(df.head)

<bound method NDFrame.head of     school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0       GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1       GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2       GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3       GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4       GP   F   16       U     GT3       T  ...     2       5        4   6  10  10
..     ...  ..  ...     ...     ...     ...  ...   ...     ...      ...  ..  ..  ..
390     MS   M   20       U     LE3       A  ...     5       4       11   9   9   9
391     MS   M   17       U     LE3       T  ...     4       2        3  14  16  16
392     MS   M   21       R     GT3       T  ...     3       3        3  10   8   7
393     MS   M   18       R     LE3       T  ...     4       5        0  11  12  10
394     MS   M   19       U     LE3       T  .

In [29]:
print(list(df.columns))

['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']


In [30]:
data=df[['G1','G2','G3','studytime','failures','absences']]
print(data.columns)

Index(['G1', 'G2', 'G3', 'studytime', 'failures', 'absences'], dtype='object')


In [31]:
import numpy as np
target='G3'
x=np.array(data.drop([target],axis=1))
y=np.array(data[target])
print(x)
print(y)

[[ 5  6  2  0  6]
 [ 5  5  2  0  4]
 [ 7  8  2  3 10]
 ...
 [10  8  1  3  3]
 [11 12  1  0  0]
 [ 8  9  1  0  5]]
[ 6  6 10 15 10 15 11  6 19 15  9 12 14 11 16 14 14 10  5 10 15 15 16 12
  8  8 11 15 11 11 12 17 16 12 15  6 18 15 11 13 11 12 18 11  9  6 11 20
 14  7 13 13 10 11 13 10 15 15  9 16 11 11  9  9 10 15 12  6  8 16 15 10
  5 14 11 10 10 11 10  5 12 11  6 15 10  8  6 14 10  7  8 18  6 10 14 10
 15 10 14  8  5 17 14  6 18 11  8 18 13 16 19 10 13 19  9 16 14 13  8 13
 15 15 13 13  8 12 11  9  0 18  0  0 12 11  0  0  0  0 12 15  0  9 11 13
  0 11  0 11  0 10  0 14 10  0 12  8 13 10 15 12  0  7  0 10  7 12 10 16
  0 14  0 16 10  0  9  9 11  6  9 11  8 12 17  8 12 11 11 15  9 10 13  9
  8 10 14 15 16 10 18 10 16 10 10  6 11  9  7 13 10  7  8 13 14  8 10 15
  4  8  8 10  6  0 17 13 14  7 15 12  9 12 14 11  9 13  6 10 13 12 11  0
 12 12  0 12  0 18 13  8  5 15  8 10  8  8 12  8 13 11 14  0 18  8 12  9
  0 17 10 11 10  0  9 14 11 14 10 12  9  9  8 10  8 10 12 10 11 11 19 12
 14 15 11 

In [32]:
import sklearn
from sklearn import linear_model
from sklearn.utils import shuffle
x_train,x_test,y_train,y_test=sklearn.model_selection.train_test_split(x,y,test_size=0.1)

In [33]:
linear=linear_model.LinearRegression()
linear.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [34]:
accuracy=linear.score(x_test,y_test)
print(accuracy)

0.865833754694218


In [35]:
print('Coefficient: \n', linear.coef_) 
print('Intercept: \n', linear.intercept_) 

Coefficient: 
 [ 0.17921149  0.96909496 -0.20772726 -0.3173718   0.04465873]
Intercept: 
 -1.7072102363948503


In [36]:
test_prediction=linear.predict(x_test)
for i in range(len(test_prediction)):
  print(test_prediction[i],x_test[i],y_test[i])
  print("The difference is ",test_prediction[i]-y_test[i],'\n')

16.339555858835933 [16 16  2  0  2] 16
The difference is  0.33955585883593287 

14.222154456376115 [15 14  2  0  2] 14
The difference is  0.2221544563761153 

5.186658639089128 [7 7 2 3 5] 7
The difference is  -1.8133413609108722 

19.458338156180332 [19 19  4  0  4] 20
The difference is  -0.5416618438196679 

12.057925111556095 [14 11  1  0 18] 13
The difference is  -0.942074888443905 

14.250670222097146 [14 14  1  0  2] 13
The difference is  1.2506702220971455 

13.134073164715359 [14 13  3  0  8] 14
The difference is  -0.8659268352846414 

8.21151671723249 [8 9 2 0 4] 10
The difference is  -1.7884832827675101 

16.457389094415046 [15 16  1  0  4] 15
The difference is  1.4573890944150456 

6.849706249145173 [ 9  7  2  1 20] 8
The difference is  -1.1502937508548268 

8.777090401715077 [9 9 1 0 8] 10
The difference is  -1.2229095982849234 

8.27289497117608 [10  9  3  0  2] 9
The difference is  -0.7271050288239191 

9.35982316322375 [ 9 10  2  0  4] 10
The difference is  -0.6401768367

In [39]:
import pickle
best=accuracy
with open('studentgrades.pickle','wb') as f:
  pickle.dump(linear,f)
for _ in range(30):
  x_train,x_test,y_train,y_test=sklearn.model_selection.train_test_split(x,y,test_size=0.1)
  linear=linear_model.LinearRegression()
  linear.fit(x_train,y_train)
  current=linear.score(x_test,y_test)
  if current>best:
    best=current
    with open('studentgrades.pickle','wb') as f:
      pickle.dump(linear,f)
print("Maximum Possible accuracy is",best)

Maximum Possible accuracy is 0.9409063272737656


In [40]:
print("Linear Regression Model Successfully Implemented")

Linear Regression Model Successfully Implemented
